name: ecmsp-dev

services:

    payment-service-db-dev:
        image: postgres:15-alpine
        container_name: payment-service-db-dev
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        ports:
            - "5432:5432"
        volumes:
            - payment-service-db:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        secrets:
            - payment-service-db-password
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_DB=payment-service-db
            - POSTGRES_PASSWORD_FILE=/run/secrets/payment-service-db-password
        env_file:
            -
                path: ./database-env.txt
                required: false

volumes:
    payment-service-db:

secrets:
    payment-service-db-password:
        file: ./database-env.txt

# docker compose -f product-docker-compose.yaml up cart-service-db
# docker compose -f product-docker-compose.yaml down -v